#line 1 "lexer.flex.cpp"

#line 3 "lexer.flex.cpp"

#define  YY_INT_ALIGNED short int
#define _CRT_SECURE_NO_WARNINGS

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 159
#define YY_END_OF_BUFFER 160
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[452] =
    {   0,
        0,    0,    6,    6,    0,    0,   10,   10,    0,    0,
        0,    0,  160,  159,  158,  123,   14,  112,  159,   15,
      147,  148,  110,  108,  137,  109,  138,  111,  153,  153,
      135,  136,  131,  113,  130,  134,  150,  157,  157,  132,
      133,  144,    1,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      145,  159,  146,    6,    7,    6,    2,    3,    4,   10,
       11,   18,   24,   16,  159,   17,  158,  141,  125,    0,
        0,  118,  121,  116,  119,  114,  120,  115,  149,  142,
        9,   13,  117,  153,  154,    0,    0,    0,  140,  128,

      124,  129,  143,  139,  157,  157,  157,  157,  157,   30,
      157,   61,  157,  157,  157,  157,  157,  157,   35,  157,
      157,  157,  157,  157,  157,  157,  157,  157,   40,  157,
       41,   44,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  122,    6,    7,    0,    7,    2,    3,   10,
       11,   11,   12,   18,   23,   28,   29,   26,   27,   22,
       20,   25,   21,    0,  127,   42,   45,    5,   13,  156,
      155,  126,  157,  157,  157,  157,   31,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,

      157,  157,  157,  157,   38,   39,   69,  157,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,   98,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,   75,
      157,  157,  157,  157,  157,  157,   54,  157,   57,   58,
      157,  157,    8,    7,   19,  157,  157,  157,  157,  157,
      157,  157,  157,  157,  157,  157,   85,  157,  157,   36,
       86,  157,  157,  157,  157,   67,  157,  157,  157,   71,
      157,  157,  157,  157,  157,   46,  157,   96,  157,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  157,  157,  157,   51,  157,   53,  157,  157,  157,

       59,  157,  157,   19,  157,  157,  157,  157,   32,   62,
       33,  157,   83,  157,  157,  157,  157,  157,  157,   37,
       66,   89,  157,   90,  157,   92,  157,  157,  157,  157,
      157,  157,  157,   72,  157,  157,  157,  157,  157,  157,
      157,  157,  157,   50,  157,  157,   52,  157,  157,   77,
      157,   78,   60,   19,  151,  157,   80,  157,  157,  157,
      157,  157,  157,  157,   87,  157,  157,   70,   91,  157,
      157,  157,  157,   47,  157,  157,  157,  157,  157,  157,
      102,  157,  157,   49,  104,  157,  157,  157,  157,   56,
      107,   19,  152,  157,  157,  157,  157,  157,  157,  157,

       65,  157,   68,  157,  157,  157,  157,  157,  157,   48,
      100,  157,  157,  157,  103,  157,  105,  106,  157,   79,
      157,  157,  157,   34,  157,   64,   88,  157,   93,   94,
       95,   97,   99,   73,  157,   74,   76,  157,  157,   82,
      157,  157,   43,  101,   55,   81,  157,  157,   63,   84,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    1,    1,    5,    6,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   26,   28,   29,   26,
       30,   30,   30,   30,   30,   31,   30,   30,   32,   30,
       30,   30,   30,   30,   33,   30,   30,   30,   30,   30,
       34,   35,   36,    1,   37,   38,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   30,   55,   56,   57,   58,   59,   60,   61,
       62,   30,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    2,    1,    3,    1,    1,    4,    1,    1,    5,
        1,    1,    1,    6,    6,    7,    7,    7,    6,    1,
        6,    1,    6,    1,    1,    7,    7,    7,    7,    8,
        8,    8,    8,    6,    4,    6,    8,    6,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    1,    1,    1
    } ;

static const flex_int16_t yy_base[468] =
    {   0,
        0,    0,   62,   63,   54,   57,  579,  578,   77,   92,
       98,   99,  587,  590,   68,   82,  582,  563,  578,  590,
      590,  590,  561,   96,  590,   97,  568,   99,   99,  124,
      562,  590,  558,  557,  556,   68,  590,    0,  545,  590,
      590,    0,  590,   91,   73,   98,  106,   61,   99,  533,
      114,  536,  109,  123,  117,  531,  142,  125,  534,  526,
      590,  507,  590,    0,  119,  566,    0,  169,  590,    0,
      159,    0,  590,  590,  204,  590,  123,  590,  547,  137,
      564,  590,  590,  590,  590,  590,  590,  590,  590,  590,
      590,    0,  590,  178,  590,  196,  185,    0,  590,  590,

      545,  590,  590,  590,    0,  533,  509,  507,  511,  538,
      518,    0,  503,  520,  165,  505,  500,  506,    0,  503,
      498,  495,   29,  502,  175,  496,  498,  492,    0,  494,
      179,    0,  490,  499,  495,  496,  500,  485,  498,  166,
      144,  500,  181,   69,  148,  122,  492,  177,  172,  484,
      185,  194,  590,    0,  533,  532,  215,    0,  232,    0,
      233,  239,  590,    0,  590,  590,  590,  590,  590,  590,
      590,  590,  590,    0,  590,  590,  590,  590,    0,  241,
        0,  590,  508,  477,  475,  479,  590,  492,  489,  473,
      474,  207,  471,  487,  482,  485,  480,  471,  478,  477,

      463,  468,  474,  477,    0,    0,    0,  462,  467,  456,
      465,  468,  467,  466,  456,  457,  463,  190,    0,  450,
      455,  464,  443,  213,  451,  457,  455,  440,  447,  442,
      452,  440,  443,  436,  438,  447,    0,  446,  430,  448,
      217,  436,  590,  590,    0,  454,  429,  444,  425,  432,
      434,  423,  439,  420,  429,  419,    0,  429,  422,    0,
        0,  431,  416,  427,  427,    0,  418,  412,  405,    0,
      413,  409,  408,  415,  411,    0,  419,    0,  420,  403,
      418,  405,  416,  411,  410,  405,  404,  403,  394,  405,
      408,  391,  402,  389,    0,  383,    0,  221,  399,  386,

        0,  397,  396,    0,  409,  398,  386,  396,    0,    0,
        0,  382,  378,  380,  384,  391,  382,  371,  375,    0,
        0,  376,  368,    0,  381,    0,  221,  371,  375,  364,
      363,  372,  373,    0,  360,  361,  374,  373,  354,  369,
      359,  368,  354,    0,  356,  364,    0,  356,  361,    0,
      359,    0,    0,    0,  359,  361,    0,  344,  353,  341,
      340,  345,  339,  354,    0,  355,  331,    0,    0,  353,
      352,  343,  337,    0,  335,  345,  343,  342,  327,  326,
        0,  339,  339,    0,    0,  341,  337,  337,  330,    0,
        0,  590,    0,  319,  328,  321,  332,  329,  321,  327,

        0,  319,    0,  327,  317,  309,  322,  309,  320,    0,
        0,  300,  318,  305,    0,  308,    0,    0,  319,    0,
      304,  298,  287,    0,  296,    0,    0,  299,    0,    0,
        0,    0,    0,    0,  292,    0,    0,  273,  270,    0,
      258,  219,    0,    0,    0,    0,  197,  167,    0,    0,
      590,  274,  282,  290,  298,  300,  308,  316,  324,  332,
      340,  348,  192,  179,  166,   82,   67
    } ;

static const flex_int16_t yy_def[468] =
    {   0,
      451,    1,  452,  452,  453,  453,  454,  454,  455,  455,
      455,  455,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  456,  456,  451,
      451,  456,  451,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      451,  451,  451,  457,  451,  457,  458,  451,  451,  459,
      460,  461,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  462,  451,  451,  451,  451,  451,  463,  451,  451,

      451,  451,  451,  451,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  451,  457,  451,  451,  451,  458,  451,  459,
      460,  460,  451,  461,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  464,  451,  451,  451,  451,  462,  451,
      463,  451,  456,  456,  456,  456,  451,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  451,  451,  465,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,

      456,  456,  456,  466,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  467,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  451,  456,  456,  456,  456,  456,  456,  456,  456,

      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
      456,  456,  456,  456,  456,  456,  456,  456,  456,  456,
        0,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451
    } ;

static const flex_int16_t yy_nxt[656] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   38,   39,   38,   38,
       38,   38,   38,   40,   14,   41,   42,   43,   44,   45,
       46,   47,   48,   49,   50,   38,   51,   38,   38,   52,
       38,   53,   54,   55,   56,   57,   58,   38,   59,   60,
       38,   38,   61,   62,   63,   65,   65,   68,   68,   77,
       68,   68,   68,  392,   68,   68,   68,   68,   73,   68,
       74,  103,  199,   14,   78,  200,  104,   68,  354,   68,
       68,   69,   68,   73,   69,   74,   66,   66,   14,   14,

       14,   14,   14,   79,   76,   76,   85,  229,   91,   87,
      121,   75,  122,   92,   94,   94,   94,   86,   88,   89,
       93,  123,  155,   77,   77,  230,   75,  111,   80,   95,
      107,  108,   75,   75,  112,   96,  113,  124,   97,   94,
       94,   94,  109,   77,  117,  125,  110,  114,  118,   77,
      115,  126,  116,  156,   95,  140,  127,  129,  119,   98,
       96,  134,  136,  147,  130,  131,  135,  120,  162,  132,
      148,  141,  304,  163,  142,  231,  137,  232,   77,  149,
      138,  139,  159,  159,  144,  245,  150,  159,  176,  159,
      223,  159,  177,   94,   94,   94,  224,  145,  181,  146,

      180,  180,  159,  145,  159,  165,  221,  166,   95,  450,
      167,   94,   94,   94,   96,  191,  192,  202,  244,  168,
      222,  226,  209,  234,  203,  210,  204,  227,  211,  236,
      212,  235,   96,  237,  239,  213,  241,  228,  169,  240,
      242,  278,  451,  170,  279,  159,  159,  451,  162,  156,
      159,  449,  159,  163,  159,  171,  180,  180,  172,  348,
      173,  174,  254,  255,  370,  159,  284,  159,  301,  285,
      448,  302,  371,  349,   64,   64,   64,   64,   64,   64,
       64,   64,   67,   67,   67,   67,   67,   67,   67,   67,
       70,   70,   70,   70,   70,   70,   70,   70,   72,   72,

       72,   72,   72,   72,   72,   72,  105,  105,  154,  154,
      447,  154,  154,  154,  154,  154,  158,  158,  158,  158,
      158,  446,  158,  158,  160,  160,  160,  160,  445,  160,
      160,  160,  161,  444,  161,  161,  161,  161,  161,  161,
      164,  443,  442,  441,  164,  164,  164,  164,  179,  440,
      179,  179,  179,  179,  179,  179,  439,  438,  437,  436,
      435,  434,  433,  432,  431,  430,  429,  428,  427,  426,
      425,  424,  423,  422,  421,  420,  419,  418,  417,  416,
      415,  414,  413,  412,  411,  410,  409,  408,  407,  406,
      405,  404,  403,  402,  401,  400,  399,  398,  397,  396,

      395,  394,  393,  391,  390,  389,  388,  387,  386,  385,
      384,  383,  382,  381,  380,  379,  378,  377,  376,  375,
      374,  373,  372,  369,  368,  367,  366,  365,  364,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  353,  352,
      351,  350,  347,  346,  345,  344,  343,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  322,  321,  320,
      319,  318,  317,  316,  315,  314,  313,  312,  311,  310,
      309,  308,  307,  306,  305,  303,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,

      286,  283,  282,  281,  280,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  261,  260,  259,  258,  257,  256,  253,  252,  251,
      250,  249,  248,  247,  246,  244,  243,  238,  233,  225,
      220,  219,  218,  217,  216,  215,  214,  208,  207,  206,
      205,  201,  198,  197,  196,  195,  194,  193,  190,  189,
      188,  187,  186,  185,  184,  183,  182,  178,  175,  157,
      153,  152,  151,  143,  133,  128,  106,  102,  101,  100,
       99,   90,   84,   83,   82,   81,  451,   71,   71,   13,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,

      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451
    } ;

static const flex_int16_t yy_chk[656] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    5,   15,
        6,    6,    5,  467,    5,    6,    5,    6,    9,    6,
        9,   36,  123,    9,   16,  123,   36,    5,  466,    5,
        6,    5,    6,   10,    6,   10,    3,    4,   10,   11,

       12,   11,   12,   16,   11,   12,   24,  144,   28,   26,
       48,    9,   48,   28,   29,   29,   29,   24,   26,   26,
       28,   48,   65,   15,   77,  144,   10,   45,   16,   29,
       44,   44,   11,   12,   45,   29,   46,   49,   29,   30,
       30,   30,   44,   57,   47,   49,   44,   46,   47,  145,
       46,   49,   46,   65,   30,   55,   49,   51,   47,   29,
       30,   53,   54,   58,   51,   51,   53,   47,   71,   51,
       58,   55,  465,   71,   55,  146,   54,  146,   77,   58,
       54,   54,   68,   68,   57,  464,   58,   68,   80,   68,
      141,   68,   80,   94,   94,   94,  141,   57,  463,   57,

       97,   97,   68,  145,   68,   75,  140,   75,   94,  448,
       75,   96,   96,   96,   94,  115,  115,  125,  157,   75,
      140,  143,  131,  148,  125,  131,  125,  143,  131,  149,
      131,  148,   96,  149,  151,  131,  152,  143,   75,  151,
      152,  218,  161,   75,  218,  159,  159,  161,  162,  157,
      159,  447,  159,  162,  159,   75,  180,  180,   75,  298,
       75,   75,  192,  192,  327,  159,  224,  159,  241,  224,
      442,  241,  327,  298,  452,  452,  452,  452,  452,  452,
      452,  452,  453,  453,  453,  453,  453,  453,  453,  453,
      454,  454,  454,  454,  454,  454,  454,  454,  455,  455,

      455,  455,  455,  455,  455,  455,  456,  456,  457,  457,
      441,  457,  457,  457,  457,  457,  458,  458,  458,  458,
      458,  439,  458,  458,  459,  459,  459,  459,  438,  459,
      459,  459,  460,  435,  460,  460,  460,  460,  460,  460,
      461,  428,  425,  423,  461,  461,  461,  461,  462,  422,
      462,  462,  462,  462,  462,  462,  421,  419,  416,  414,
      413,  412,  409,  408,  407,  406,  405,  404,  402,  400,
      399,  398,  397,  396,  395,  394,  389,  388,  387,  386,
      383,  382,  380,  379,  378,  377,  376,  375,  373,  372,
      371,  370,  367,  366,  364,  363,  362,  361,  360,  359,

      358,  356,  355,  351,  349,  348,  346,  345,  343,  342,
      341,  340,  339,  338,  337,  336,  335,  333,  332,  331,
      330,  329,  328,  325,  323,  322,  319,  318,  317,  316,
      315,  314,  313,  312,  308,  307,  306,  305,  303,  302,
      300,  299,  296,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  277,
      275,  274,  273,  272,  271,  269,  268,  267,  265,  264,
      263,  262,  259,  258,  256,  255,  254,  253,  252,  251,
      250,  249,  248,  247,  246,  242,  240,  239,  238,  236,
      235,  234,  233,  232,  231,  230,  229,  228,  227,  226,

      225,  223,  222,  221,  220,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  204,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  191,  190,  189,
      188,  186,  185,  184,  183,  156,  155,  150,  147,  142,
      139,  138,  137,  136,  135,  134,  133,  130,  128,  127,
      126,  124,  122,  121,  120,  118,  117,  116,  114,  113,
      111,  110,  109,  108,  107,  106,  101,   81,   79,   66,
       62,   60,   59,   56,   52,   50,   39,   35,   34,   33,
       31,   27,   23,   19,   18,   17,   13,    8,    7,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,

      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451,  451,  451,  451,  451,  451,
      451,  451,  451,  451,  451
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[160] =
    {   0,
0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 6 "lexer.l"

#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <string.h>

void printMLComment(const char* comment);
void printONComment(const char* comment);
void printKeyword(const char* keyword);
void printLogicOperator(const char* o);
void printComparisonOperator(const char* o);
void printArithmeticOperator(const char* o);
void printInteger(int i);
void printLong(long int i);
void printFloat(float f);
void printDouble(double d);
void printChar(const char c);
void printString(const char* str);
void printRawString(const char* str);
void printIdentifier(const char* id);
void printBackticksIdentifier(const char* id);
void printErr(const char* errMsg, int lineNum);
void removeChar(char * str, char charToRemmove);

#line 797 "lexer.flex.cpp"
/* Note: There's no octal integer literals in Kotlin */

#line 800 "lexer.flex.cpp"

#define INITIAL 0
#define RAW_STRING 1
#define BACKTICKS_IDENTIFIER 2
#define MULTILINE_COMMENT 3
#define STRING 4
#define CHAR 5

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 46 "lexer.l"




#line 51 "lexer.l"
int currentInteger;
long int currentLong;
double currentDouble;
float currentFloat;
char currentString[1000];
char buffer[100];



#line 1034 "lexer.flex.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 452 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 451 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 60 "lexer.l"
{
                                            currentString[0] = '\0';
                                            BEGIN(BACKTICKS_IDENTIFIER);
                                        }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 65 "lexer.l"
{
                                            strcat(currentString, yytext);
                                        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 69 "lexer.l"
{
                                            printErr("Error! Name contains illegal characters", yylineno);
                                        }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 73 "lexer.l"
{
                                            printBackticksIdentifier(currentString);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "lexer.l"
{
                                            currentString[0] = '\0';
                                            BEGIN(RAW_STRING);
                                        }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 84 "lexer.l"
{
                                            strcat(currentString, yytext);
                                        }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 88 "lexer.l"
{
                                            strcat(currentString, yytext);
                                        }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 92 "lexer.l"
{
                                            printRawString(currentString);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 97 "lexer.l"
{
                                            currentString[0] = '\0';
                                            BEGIN(MULTILINE_COMMENT);
                                        }
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 102 "lexer.l"
{
                                            strcat(currentString, yytext);
                                        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 106 "lexer.l"
{
                                            strcat(currentString, yytext);
                                        }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "lexer.l"
{
                                            printMLComment(currentString);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 115 "lexer.l"
{
                                            printONComment(yytext);
                                        }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 119 "lexer.l"
{
                                            currentString[0] = '\0';
                                            BEGIN(STRING);
                                        }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 124 "lexer.l"
{
                                            currentString[0] = '\0';
                                            BEGIN(CHAR);
                                        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 129 "lexer.l"
{
                                            printString(currentString);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 134 "lexer.l"
{
                                            if (currentString[1] != '\0')
                                            {
                                                printErr("Error! More than one character in a char literal", yylineno);
                                            }
                                            else
                                            {
                                                printChar(currentString[0]);
                                            }
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "lexer.l"
{
                                            strcat(currentString, yytext);
                                        }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 150 "lexer.l"
{
                                            sscanf(yytext, "%c", &buffer);
                                            strcat(currentString, buffer);
                                        }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 155 "lexer.l"
{
                                            strcat(currentString, "\n");
                                        }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 159 "lexer.l"
{
                                            strcat(currentString, "\t");
                                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 164 "lexer.l"
{
                                            strcat(currentString, "\b");
                                        }
	YY_BREAK
case 23:
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 168 "lexer.l"
{
                                            strcat(currentString, "\$");
                                        }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 172 "lexer.l"
{
                                            printErr("Error! Expected end of string/char but found end of line!", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(CHAR):
case YY_STATE_EOF(MULTILINE_COMMENT):
#line 177 "lexer.l"
{
                                            printErr("Error! expected end of string but found end of file!", yylineno);
                                            BEGIN(INITIAL);
                                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 182 "lexer.l"
{
                                            strcat(currentString, "\r");
                                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 186 "lexer.l"
{
                                            strcat(currentString, "\0");
                                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 190 "lexer.l"
{
                                            strcat(currentString, "\\");
                                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 194 "lexer.l"
{
                                            strcat(currentString, "\"");
                                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 198 "lexer.l"
{
                                            strcat(currentString, "\'");
                                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 203 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 204 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 205 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 206 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 207 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 208 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 209 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 210 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 211 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 212 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 213 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 214 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 215 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 216 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 217 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 218 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 219 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 220 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 221 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 222 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 223 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 224 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 225 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 226 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 227 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 228 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 229 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 230 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 231 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 232 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 233 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 235 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 236 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 237 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 238 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 239 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 240 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 241 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 242 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 243 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 244 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 245 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 246 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 247 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 248 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 249 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 250 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 251 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 252 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 254 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 255 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 256 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 257 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 258 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 259 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 260 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 261 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 262 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 263 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 264 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 265 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 266 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 267 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 268 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 269 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 270 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 271 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 272 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 273 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 274 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 275 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 276 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 277 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 278 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 279 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 280 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 281 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 282 "lexer.l"
{ printKeyword(yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 284 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 285 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 286 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 287 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 288 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 290 "lexer.l"
{ printf("Found assign operator: %s\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 292 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 293 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 294 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 295 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 296 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 298 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 299 "lexer.l"
{ printArithmeticOperator(yytext); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 301 "lexer.l"
{ printLogicOperator(yytext); }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 302 "lexer.l"
{ printLogicOperator(yytext); }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 303 "lexer.l"
{ printLogicOperator(yytext); }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 305 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 306 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 307 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 308 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 309 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 310 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 311 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 312 "lexer.l"
{ printComparisonOperator(yytext); }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 314 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 315 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 317 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 318 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 319 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 320 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 321 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 323 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 324 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 325 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 326 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 327 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 329 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 331 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 332 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 334 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 148:
YY_RULE_SETUP
#line 335 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 337 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 338 "lexer.l"
{ printf("%s\n", yytext); }
	YY_BREAK
case 151:
YY_RULE_SETUP
#line 340 "lexer.l"
{
                                            buffer[0] = '\0';
                                            strcat(buffer, yytext);
                                            removeChar(buffer, '_');
                                            currentDouble = atof(buffer);
                                            printDouble(currentFloat);
                                        }
	YY_BREAK
case 152:
YY_RULE_SETUP
#line 348 "lexer.l"
{
                                            buffer[0] = '\0';
                                            strcat(buffer, yytext);
                                            removeChar(buffer, '_');
                                            currentFloat = atof(buffer);
                                            printFloat(currentFloat);
                                        }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 357 "lexer.l"
{
                                            buffer[0] = '\0';
                                            strcat(buffer, yytext);
                                            removeChar(buffer, '_');
                                            currentInteger = atoi(buffer);
                                            printInteger(currentInteger);
                                        }
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 365 "lexer.l"
{
                                            buffer[0] = '\0';
                                            strcat(buffer, yytext);
                                            removeChar(buffer, '_');
                                            char *p;
                                            currentLong = strtol(buffer, &p, 10);;
                                            printLong(currentLong);
                                        }
	YY_BREAK
case 155:
YY_RULE_SETUP
#line 374 "lexer.l"
{
                                            buffer[0] = '\0';
                                            strcat(buffer, yytext);
                                            currentInteger = atoi(buffer);
                                            printInteger(currentInteger);
                                        }
	YY_BREAK
case 156:
YY_RULE_SETUP
#line 381 "lexer.l"
{
                                            buffer[0] = '\0';
                                            strcat(buffer, yytext);
                                            currentInteger = atoi(buffer);
                                            printInteger(currentInteger);
                                        }
	YY_BREAK
case 157:
YY_RULE_SETUP
#line 388 "lexer.l"
{
                                            printIdentifier(yytext);
                                        }
	YY_BREAK
case 158:
/* rule 158 can match eol */
YY_RULE_SETUP
#line 393 "lexer.l"
{ /* no action */ }
	YY_BREAK
case 159:
YY_RULE_SETUP
#line 395 "lexer.l"
ECHO;
	YY_BREAK
#line 2023 "lexer.flex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(RAW_STRING):
case YY_STATE_EOF(BACKTICKS_IDENTIFIER):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 452 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 452 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 451);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 395 "lexer.l"


void removeChar(char * str, char charToRemmove){
    int i, j;
    int len = strlen(str);
    for(i=0; i<len; i++)
    {
        if(str[i] == charToRemmove)
        {
            for(j=i; j<len; j++)
            {
                str[j] = str[j+1];
            }
            len--;
            i--;
        }
    }
    
}

void printMLComment(const char* comment)
{
    printf("Found multiline comment: \n\"%s\"\n\n", comment);
}

void printONComment(const char* comment)
{
    printf("Found one line comment: \n\"%s\"\n\n", comment);
}

void printKeyword(const char* keyword)
{
    printf("Found keyword: %s\n", keyword);
}

void printLogicOperator(const char* o)
{
    printf("Found logic operator: %s\n", o);
}

void printComparisonOperator(const char* o)
{
    printf("Found comparison operator: %s\n", o);
}

void printArithmeticOperator(const char* o)
{
    printf("Found arithmetic operator: %s\n", o);
}

void printInteger(int i)
{
    printf("Found integer: %d\n", i);
}

void printLong(long int i)
{
    printf("Found long integer: %ld\n", i);
}

void printFloat(float f)
{
    printf("Found float: %f\n", f);
}

void printDouble(double d)
{
    printf("Found double: %lf\n", d);
}

void printChar(const char c)
{
    printf("Found char: %c\n", c);
}

void printString(const char* str)
{
    printf("Found string: \n%s\n\n", str);
}

void printRawString(const char* str)
{
    printf("Found RAW string: \n\"\"\"%s\"\"\"\n\n", str);
}

void printIdentifier(const char* id)
{
    printf("Found identifier: %s\n", id);
}

void printBackticksIdentifier(const char* id)
{
    printf("Found identifier in backticks: %s\n", id);
}

void printErr(const char* errMsg, int lineNum)
{
    if (lineNum >= 0)
    {
        printf("Error in line %d\n", lineNum);
    }

    printf("Error message: %s\n", errMsg);
}

int main(int argc, char* argv[])
{
    //yyin = fopen(argv[1], "r");
    yyin = fopen("text.txt", "r");
    yylex();
    return 0;
}
